name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: GitHub Action for LaTeX
        uses: xu-cheng/latex-action@4.0.0
        with:
          root_file: "*.tex"
          working_directory: slides
          continue_on_error: true
          latexmk_use_lualatex: true      
      - name: Release PDF file
        uses: softprops/action-gh-release@v2
        with:
          files: "slides/*.pdf"

